In [2]:
#Difficulty level Beginner

In [3]:
#import the numpy package under the name np
import numpy as np

In [5]:
#create a null vector of size 10
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#create a vector with values ranging from 10 to 49
import numpy as np
v = np.arange(10,49)
print("Vector:")
print(v)

Vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [7]:
#find the shape of the previous array
print("Shape of vector: ",v.shape)

Shape of vector:  (39,)


In [8]:
#find the type of the previous array
type(v)

numpy.ndarray

In [9]:
#print the numpy version and configuration
import numpy as np
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

In [10]:
#print the dimension of the previous array
v.ndim

1

In [11]:
#create a boolean array with all the true values
import numpy as np
bool_array = np.array(["Kashish",123,True,0.124],dtype=bool)
print(bool_array)

[ True  True  True  True]


In [12]:
#create a 2 dimensional array
array2d = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26]])
array2d

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [13]:
#create a three dimensional array
array3d = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(array3d)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [1]:
#difficulty level easy

In [18]:
#reverse a vector(first element becomes last)
import numpy as np
v = np.arange(11,22)
print("Array: ")
print(v)
print("Array in reverse order: ")
v = v[::-1]
print(v)

Array: 
[11 12 13 14 15 16 17 18 19 20 21]
Array in reverse order: 
[21 20 19 18 17 16 15 14 13 12 11]


In [3]:
#create a null vector of size 10 but the fifth value which is 1
import numpy as np
k = np.zeros(10)
k[4] = 1
print(k)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#create a 3x3 identity matrix
import numpy as np
id_matrix =np.identity(3)
print("3x3 identity matrix: ")
print(id_matrix)

3x3 identity matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#convert the data type of the array from int to float
int_array = np.array([10,20,30,40,50,60,70,80,90,100])
print(int_array.dtype)
float_array = int_array.astype(np.float64)
print(float_array.dtype)

int32
float64


In [8]:
#multiply the two arrays
import numpy as np
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
resultant_arr = np.multiply(arr1,arr2)
print("The resultant array is: ",resultant_arr)

The resultant array is:  [[ 0.  8.  3.]
 [28. 10. 72.]]


In [9]:
#make an array by comparing both arrays
import numpy as np
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
print(np.intersect1d(arr1,arr2))

[1. 2. 4.]


In [10]:
#extract all odd numbers 
arr = np.arange(0,10)
resultant_arr = []
for i in arr:
    if i % 2 != 0:
        resultant_arr.append(i)
print(np.array(resultant_arr))

[1 3 5 7 9]


In [13]:
#replace all odd numbers to -1
import numpy as np
arr = np.arange(0,10)
print(arr)
arr[arr % 2 != 0] = -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [16]:
#replace the values of indexes 5,6,7,8 to 12
import numpy as np
arr = np.array([31,32,33,34,35,36,37,38,39,40])
arr[5:9] = 12
print(arr)


[31 32 33 34 35 12 12 12 12 40]


In [17]:
#create a 2D array with 1 on the border and 0 on the inside
import numpy as np
arr_2D = np.ones((5,5))
print("2D array: ")
arr_2D[1:-1,1:-1] = 0
print(arr_2D)


2D array: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
