In [2]:
#Difficulty level Beginner

In [3]:
#import the numpy package under the name np
import numpy as np

In [5]:
#create a null vector of size 10
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#create a vector with values ranging from 10 to 49
import numpy as np
v = np.arange(10,49)
print("Vector:")
print(v)

Vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [7]:
#find the shape of the previous array
print("Shape of vector: ",v.shape)

Shape of vector:  (39,)


In [8]:
#find the type of the previous array
type(v)

numpy.ndarray

In [9]:
#print the numpy version and configuration
import numpy as np
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

In [10]:
#print the dimension of the previous array
v.ndim

1

In [11]:
#create a boolean array with all the true values
import numpy as np
bool_array = np.array(["Kashish",123,True,0.124],dtype=bool)
print(bool_array)

[ True  True  True  True]


In [12]:
#create a 2 dimensional array
array2d = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26]])
array2d

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [13]:
#create a three dimensional array
array3d = np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(array3d)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
